### PR TITLE
Fix regex with stars

### PR DESCRIPTION
**Pull request by maciex**
This pull request fixes problems with regular expressions containing star ('*') sign.

Before the fix the start was detected as an operator.
After the fix the 'rgx:' is first searched, then we continue to search for other operators.
This way the start won't be escaped(?).

### CODE REVIEW

**Comment by maciex** [comment]
One question about the `test/test-filter-operators.html`... Maybe something is wrong.
I'm not 100% sure how the tests are working, but the table in that HTML source file contains 7 rows, yet my browser shows only 6 rows.
Table row:
```
<tr>
    <td><strong>Adelaide</strong></td>
    <td>Alice Springs</td>
    <td>1533</td>
    <td>2</td>
    <td>20.25</td>
</tr>
```
is somehow not shown.

Because of that it was quite hard to get the right expected values in the test parameters.

**Comment by koalyptus** [comment]
I see 7 rows on my browser... can't reproduce the issue on `/test-filter-operators.html`

**Comment by maciex** [comment]
About the missing rows. I'll create a separate pull request, where we can discuss further.

All the steps you mentioned above done (merge, bump, grunt).

**Comment by koalyptus** [comment]
@maciex this PR can be closed as #541 contains these changes.
cheers

**Comment by maciex** [comment]
Closing. Changes will be merged under #541

**Pull request closed without merging**
