### PR TITLE
URL Encode State Hash

### PR DESCRIPTION
**Pull request by archisgore**
You'll notice a mild asymmetry in how hash was
saved vs retrieved.

The retrieval was:
    JSON.parse(decodeUrlComponent(hash))

The save was:
    JSON.stringify(hash)

I modified it to:
    JSON.stringify(encodeUrlComponent(hash))

The reason I noticed this is in one of my apps,
I wanted to be able to copy/share a stateful filter URL.

However without the url encoding, those auto-parsers
of URLs were missing the full filter.

TESTING CONDUCTED:
1. Updated the Hash unit tests to both parse the
   encoded string, as well as generate it.

2. Ran "grunt", which has built/tested/jslinted
   the code.

### CODE REVIEW

**Comment by koalyptus** [comment]
Thanks a lot for pointing this out. Can you please bump the version in package.json to 0.2.57, run grunt, commit and push again?
Then it's good to go, 
Cheers

**Comment by koalyptus** [comment]
Tx for having updated the unit tests too 👍

**Comment by archisgore** [comment]
Done! You can tell I don't write a lot of node.js. :-) Keep forgetting the package version.

**Comment by koalyptus** [comment]
👌

**Pull request merged**
